#!/bin/bash
#SBATCH --job-name=rtx-distribution-test        # name
#SBATCH --nodes=2                               # nodes
#SBATCH --ntasks-per-node=1                     # crucial - only 1 task per dist per node!
#SBATCH --partition=clara       
#SBATCH --gres=gpu:rtx2080ti:1                  # number of gpus
#SBATCH --time 01:15:00                         # maximum execution time (HH:MM:SS)
#SBATCH --output=clara_rtx/%x-%j.out            # output file name
#SBATCH --mail-type=ALL

# load modules
module load Python
srun pip install --user -r requirements.txt

MASTER_PORT=$(expr 10000 + $(echo -n $SLURM_JOBID | tail -c 4))
MASTER_ADDR=$(scontrol show hostnames "$SLURM_JOB_NODELIST" | head -n 1)
IP_ADDRESS=$(srun hostname --ip-address | head -n 1)
echo "MASTER_ADDR="$MASTER_ADDR

echo "NETWORK_ADRESS"

GPUS_PER_NODE=1

export NCCL_DEBUG=INFO
echo "srun bash -c \"python -m torch.distributed.run --nproc_per_node $GPUS_PER_NODE --nnodes $SLURM_NNODES --node_rank $SLURM_PROCID --master_addr $IP_ADDRESS --master_port $MASTER_PORT torch-distributed-gpu-test_no_flock.py\""
LOGLEVEL=INFO

export NCCL_SOCKET_IFNAME=$IP_ADDRESS

srun --jobid $SLURM_JOBID bash -c "python -m torch.distributed.run --nproc_per_node $GPUS_PER_NODE --nnodes $SLURM_NNODES --node_rank $SLURM_PROCID --master_addr $IP_ADDRESS --master_port $MASTER_PORT torch-distributed-gpu-test_no_flock.py"

#srun --jobid $SLURM_JOBID bash -c "python -m torch.distributed.run --rdzv_id=$SLURM_JOBID --rdzv_backend=c10d --rdzv_endpoint=$MASTER_ADDR:$MASTER_PORT --nproc_per_node $GPUS_PER_NODE --nnodes $SLURM_NNODES  torch-distributed-gpu-test_no_flock.py"
